[profile.default]
src = "src"
out = "out"
libs = ["lib"]
test = 'test'
cache_path  = 'cache_forge'

solc = "0.8.28"
evm_version = "shanghai"

[fmt]
line_length = 120
tab_width = 4
bracket_spacing = true
int_types = "long"
func_attrs_with_params_multiline = true
quote_style = "double"
number_underscore = "preserve"